language: node_js
node_js:
- "8"
- "10"
script:
- npm run test:ci
- npm run build
after_script:
- cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
cache: false
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    tags: true
