name: 🐛 Bug Report
description: Create a report to help us improve GeoStyler
labels: [bug]
assignees: [jansule, KaiVolland]
body:
    - type: textarea
      id: description
      attributes:
          label: Description
          description: |
            A clear and concise description of what the bug is.
            If applicable, add screenshots to help explain your problem.
      validations:
          required: true
    - type: textarea
      id: expected-behaviour
      attributes:
          label: Expected behaviour
          description: A clear and concise description of what you expected to happen.
      validations:
          required: true
    - type: textarea
      id: how-to-reproduce
      attributes:
          label: How to reproduce
          description: |
            In which environment(s) does the problem occur: desktop or mobile? Which OS? Which browsers/versions?
            Steps to reproduce the behavior:
            1. Go to '...'
            2. Click on '....'
            3. Scroll down to '....'
            4. See error

            Add screenshots if necessary.
      validations:
          required: true
    - type: textarea
      id: possible-solution
      attributes:
          label: Possible Solution
          description: |
            Optional: only if you have suggestions on a fix/reason for the bug.
            Don't hesitate to create a pull request with your solution, it helps get faster feedback.
    - type: textarea
      id: additional-context
      attributes:
          label: Additional Context
          description: Add any other context about the problem here.
