name: Release

on:
  workflow_dispatch:

jobs:
  release:
    uses: geostyler/workflows/.github/workflows/release.yml@main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  notify-discord:
    needs: release
    if: needs.release.outputs.tag_name != ''
    uses: geostyler/workflows/.github/workflows/notify-discord.yml@main
    secrets:
      discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
